Import Libraries 

In [3]:
import pandas as pd
import numpy as np

Import Dataset

In [4]:
data = pd.read_csv('NumpyExerciseData.csv')
data

X0     X1     X2  X3  X4   X5   y  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0    1  5.768  62.55   0  28  2.6  28         NaN         NaN         NaN   
1    1  8.949  66.91   0  27 -2.0  46         NaN         NaN         NaN   
2    1  1.024  34.42   0  20 -3.4  14         NaN         NaN         NaN   
3    1  4.534  47.93   0  10  1.1  17         NaN         NaN         NaN   
4    1  8.641  35.26   0  30  3.8  32         NaN         NaN         NaN   
5    1  1.063  42.14   0   6 -2.1   8         NaN         NaN         NaN   
6    1  5.306  39.80   0  29 -1.8  30         NaN         NaN         NaN   
7    1  4.309  36.14   0  12 -3.4  22         NaN         NaN         NaN   
8    1  3.739  44.53   0  39  1.9  24         NaN         NaN         NaN   
9    1  3.816  60.01   0  10 -3.4  24         NaN         NaN         NaN   
10   1  8.539  36.90   0  31 -3.0  43         NaN         NaN         NaN   
11   1  7.129  35.77   0  38  3.5  30         NaN         NaN         NaN   
12   1  4.249  37.17   0  23  0.8  20         NaN         NaN         NaN   
13   1 -2.990  42.41   0  20 -3.1   2         NaN         NaN         NaN   
14   1  0.356  57.67   0  26 -3.8  19         NaN         NaN         NaN   
15   1  5.487  35.25   0  10 -2.8  24         NaN         NaN         NaN   
16   1  5.699  62.15   0  13  2.4  22         NaN         NaN         NaN   
17   1 -0.373  38.38   1  42  2.0  23         NaN         NaN         NaN   
18   1  3.900  40.53   0  23 -2.5  25         NaN         NaN         NaN   
19   1  3.616  35.91   1  16  3.1  23         NaN         NaN         NaN   
20   1  9.103  59.60   0  14  2.2  34         NaN         NaN         NaN   
21   1  2.714  43.54   0  37  2.1  19         NaN         NaN         NaN   
22   1  6.885  35.66   1  20 -3.7  46         NaN         NaN         NaN   
23   1 -0.850  43.94   1  31 -3.2  26         NaN         NaN         NaN   
24   1  5.511  58.96   0   6 -3.8  28         NaN         NaN         NaN   
25   1  5.225  45.25   0  24 -1.3  28         NaN         NaN         NaN   
26   1  7.982  43.71   0  27  2.0  33         NaN         NaN         NaN   
27   1  4.361  52.71   0  22 -2.5  28         NaN         NaN         NaN   
28   1  2.853  51.12   0  42  2.3  22         NaN         NaN         NaN   
29   1  2.777  38.60   1  24 -2.5  33         NaN         NaN         NaN   
30   1  1.977  49.07   0  41 -3.6  28         NaN         NaN         NaN   
31   1  3.784  45.44   0  12 -1.9  20         NaN         NaN         NaN   
32   1  3.043  62.50   0  25 -1.9  25         NaN         NaN         NaN   
33   1  5.618  52.44   0  27  1.1  28         NaN         NaN         NaN   
34   1  7.374  38.25   0  36  3.1  31         NaN         NaN         NaN   
35   1  3.090  56.77   0  49 -1.7  33         NaN         NaN         NaN   
36   1  6.178  61.51   1   6 -2.5  41         NaN         NaN         NaN   
37   1  4.605  58.22   0  41  0.2  32         NaN         NaN         NaN   
38   1  1.968  65.84   0  76  3.5  33         NaN         NaN         NaN   
39   1  3.610  45.18   1  43  2.5  36         NaN         NaN         NaN   
40   1  9.896  65.18   0  69  2.3  58         NaN         NaN         NaN   
41   1 -0.256  53.70   0  13  0.3   5         NaN         NaN         NaN   
42   1  4.545  39.25   1  18  2.2  29         NaN         NaN         NaN   
43   1  3.121  36.89   0  20  4.1  10         NaN         NaN         NaN   
44   1  4.698  40.65   0   8 -1.8  20         NaN         NaN         NaN   
45   1 -0.328  49.64   0  18  0.5   6         NaN         NaN         NaN   
46   1  5.216  44.49   1  11  3.2  28         NaN         NaN         NaN   
47   1 -2.111  51.31   0  25  2.6  -1         NaN         NaN         NaN   
48   1  6.804  36.12   0  24  3.0  25         NaN         NaN         NaN   
49   1  5.643  39.06   0  35 -1.9  34         NaN         NaN         NaN   

    Unnamed: 10  
0           NaN  
1           NaN  
2           NaN  
3   

In [5]:
data.shape

(50, 11)

In [6]:
np_Arr = data.to_numpy()

In [7]:
np_Arr.shape

(50, 11)

Newton Method
Perform this matrix computation -> ((X'X)^-1)*X'y, use only X and y values from rows 2 to 41

In [91]:
#Train-test Split
train_Arr = np_Arr[:42,0:6] #X Values
train_Y = np_Arr[:42,6:7] #y column
print("Shape 'X' Values (Train) : ",train_Arr.shape)
print("Shape 'y' Value (Train) : ",train_Y.shape)

test_Arr = np_Arr[43:,0:6] 
test_Y = np_Arr[43:,6:7]
print("Shape 'X' Values (Test) : ",train_Arr.shape)
print("Shape 'y' Value (Test) : ",train_Y.shape)


Shape 'X' Values (Train) :  (42, 6)
Shape 'y' Value (Train) :  (42, 1)
Shape 'X' Values (Test) :  (42, 6)
Shape 'y' Value (Test) :  (42, 1)


In [59]:
# X'
train_Trans = train_Arr.transpose()
train_Trans.shape

(6, 42)

In [60]:
test_Trans = test_Arr.transpose()
test_Trans.shape

(6, 7)

In [62]:
#Inverse
train_Inv = np.linalg.inv(np.dot(train_Trans,train_Arr))
train_Inv.shape

(6, 6)

Weight - Newton's Method

In [14]:
# ((X'X)^-1)*X'y
w = np.dot(train_Inv,np.dot(train_Trans,train_Y))
w

array([[-7.81255606],
       [ 3.26009384],
       [ 0.16690469],
       [12.18239059],
       [ 0.38161309],
       [-1.5843724 ]])

In [15]:
print(train_Trans.shape)
print(train_Inv.shape)
print(train_Y.shape)

(6, 42)
(6, 6)
(42, 1)


Y Value Prediction - Newton's Method

In [81]:
y_Train_Pred = np.dot(train_Arr,w)
y_Test_Pred = np.dot(test_Arr,w)
print(y_Train_Pred)
print(y_Test_Pred)

[[27.99735178]
 [46.0019147 ]
 [14.28976738]
 [17.04177241]
 [31.67075174]
 [ 8.30314785]
 [30.04695842]
 [22.233347  ]
 [23.68180355]
 [23.84690947]
 [42.76729129]
 [30.35482768]
 [19.75303311]
 [ 2.06200743]
 [18.9159862 ]
 [24.21134276]
 [22.29832155]
 [22.41862645]
 [24.40448903]
 [23.34613623]
 [33.66856162]
 [19.09487106]
 [46.26184153]
 [25.83254426]
 [28.30481522]
 [27.99226972]
 [32.63972557]
 [27.55867831]
 [22.40435261]
 [32.98528128]
 [28.17253988]
 [19.69745273]
 [25.09008735]
 [27.81587681]
 [31.43799708]
 [33.12878759]
 [41.02761124]
 [32.24662927]
 [33.04960476]
 [36.12795901]
 [58.01542692]
 [ 4.80130013]]
[[ 9.65564574]
 [20.19281545]
 [ 5.48013131]
 [27.92782592]
 [-0.7097756 ]
 [24.80331676]
 [33.47021636]]


Error Computation (both Training and Test Error)
Generate y values from the new generated w values
Compute the SSR, MSR and RMSE between the generated y values and the actual values both for the data from rows 2 to 41 and the data from rows 43 to 51

In [76]:
newt_ssr_train = np.sum(np.power(np.subtract(train_Y,y_Train_Pred),2))
newt_ssr_test = np.sum(np.power(np.subtract(test_Y,y_Test_Pred),2))
print("SSR - Newton's Method (Train) : ",newt_ssr_train)
print("SSR - Newton's Method (Test) : ",newt_ssr_test)

SSR - Newton's Method (Train) :  2.9540159678699496
SSR - Newton's Method (Test) :  0.834815415560693


In [74]:
# MSR and RMSE
newt_msr_train = np.mean(np.power(np.subtract(train_Y,y_Train_Pred),2))
newt_msr_test = np.mean(np.power(np.subtract(test_Y,y_Test_Pred),2))
print("MSR - Newton's Method (Train) : ",newt_msr_train)
print("MSR - Newton's Method (Test) : ",newt_msr_test)

MSR - Newton's Method (Train) :  0.07033371352071309
MSR - Newton's Method (Test) :  0.11925934508009901


In [75]:
newt_rmse_train = np.sqrt(newt_msr_train)
newt_rmse_test = np.sqrt(newt_msr_test)
print("RMSE - Newton's Method (Train) : ",newt_rmse_train)
print("RMSE - Newton's Method (Test) : ",newt_rmse_test)

RMSE - Newton's Method (Train) :  0.2652050405265954
RMSE - Newton's Method (Test) :  0.3453394635429015


Regularized Newton
Next step perform the matrix computation -> ((X'X+lambda*I)^-1)*X'y, using only X and y values from rows 2 to 41
Use lambda as 0.17
Compute and report both training and test errors for the regularized newton computation

In [79]:
# ((X'X+lambda*I)^-1)*X'y
reg_Newt_Train_W = np.dot(np.linalg.inv(np.add(np.dot(train_Trans,train_Arr),np.dot(0.17,np.identity(train_Arr.shape[1])))),np.dot(train_Trans,train_Y))
reg_Newt_Train_W
print("Regularized Newton's Method - Weights : ",reg_Newt_Train_W)

Regularized Newton's Method - Weights :  [[-6.76458303]
 [ 3.23443812]
 [ 0.15156595]
 [11.6759603 ]
 [ 0.37862746]
 [-1.5650966 ]]


In [82]:
y_Reg_Newt_Train_Pred = np.dot(train_Arr,reg_Newt_Train_W)
y_Reg_Newt_Test_Pred = np.dot(test_Arr,reg_Newt_Train_W)
print("Y - Prediction - Regularized Newton's Method : ",y_Reg_Newt_Train_Pred)
print("Y - Prediction - Regularized Newton's Method : ",y_Reg_Newt_Test_Pred)


Y - Prediction - Regularized Newton's Method :  [[27.90442388]
 [45.67481598]
 [14.65825923]
 [17.22958364]
 [31.93986893]
 [ 8.61908135]
 [30.22704069]
 [22.51506218]
 [23.8710003 ]
 [23.78110841]
 [42.87980875]
 [30.62524582]
 [20.0686052 ]
 [ 2.41670754]
 [18.91936626]
 [24.49402371]
 [22.25422863]
 [22.2941932 ]
 [24.61386666]
 [23.25607865]
 [33.56940962]
 [19.33537669]
 [45.94873213]
 [25.5676731 ]
 [28.21586557]
 [28.11539999]
 [32.77039794]
 [27.57238841]
 [22.51395146]
 [32.74365814]
 [28.22531596]
 [19.87890057]
 [24.99005401]
 [27.85594388]
 [31.66235042]
 [33.04763956]
 [40.40106368]
 [32.16488068]
 [32.87774233]
 [35.80368785]
 [57.64805792]
 [ 4.99912022]]
Y - Prediction - Regularized Newton's Method :  [[10.07701936]
 [20.43815661]
 [ 5.73100093]
 [27.68196849]
 [-0.41919772]
 [25.1088653 ]
 [33.63316198]]


Compute R-squared values for both Newton and Regularized Newton on both train and test datasets
Look up how to compute R-squared values in excel

In [85]:
ssr_reg_train= np.sum(np.power(np.subtract(train_Y,y_Reg_Newt_Train_Pred),2))
ssr_reg_test = np.sum(np.power(np.subtract(test_Y,y_Reg_Newt_Test_Pred),2))
print("SSR - Regularized Newton's Method (Train) : ",ssr_reg_train)
print("SSR - Regularized Newton's Method (Test) : ",ssr_reg_test)

SSR - Regularized Newton's Method (Train) :  5.184206219816345
SSR - Regularized Newton's Method (Test) :  0.8551708105164406


In [86]:
sst_train = np.sum(np.power(train_Y-np.mean(train_Y),2))
sst_test = np.sum(np.power(test_Y-np.mean(test_Y),2))
print("SST - Regularized Newton's Method (Train) : ",sst_train)
print("SST - Regularized Newton's Method (Test) : ",sst_test)


SST - Regularized Newton's Method (Train) :  4605.071428571428
SST - Regularized Newton's Method (Test) :  975.7142857142856


In [87]:
R_squared_Newt_Train = 1 - (newt_ssr_train / sst_train) #For Newton Train Set
R_squared_Newt_Test = 1 - (newt_ssr_test / sst_test) 
print("R-Squared - Newton's Method (Train) : ",R_squared_Newt_Train)
print("R-Squared - Newton's Method (Test) : ",R_squared_Newt_Test)

R-Squared - Newton's Method (Train) :  0.9993585298265859
R-Squared - Newton's Method (Test) :  0.99914440586985


In [88]:
R_squared_Newt_Reg_Train= 1 - (ssr_reg_train / sst_train) #For Regularized Newton Train Set
R_squared_Newt_Reg_Test = 1 - (ssr_reg_test / sst_test)
print("R-Squared - Regularized Newton's Method (Train) : ",R_squared_Newt_Reg_Train)
print("R-Squared - Regularized Newton's Method (Test) : ",R_squared_Newt_Reg_Test)


R-Squared - Regularized Newton's Method (Train) :  0.9988742397810266
R-Squared - Regularized Newton's Method (Test) :  0.9991235438252394


Let's try some more things
For each of the below report the following, MSR on train, MSR on test, R-squared on train and R-squared on test
1. Use only rows 2 to 41 for training and rows 42 to 51 for testing and lambda as 0.83
2. Use only rows 2 to 26 for training and rows 27 to 51 for testing and lambda as 0.17
3. Use only rows 2 to 26 for training and rows 27 to 51 for testing and lambda as 0.83
4. Use only rows 2 to 11 for training and rows 12 to 51 for testing and lambda as 0.17
5. Use only rows 2 to 11 for training and rows 12 to 51 for testing and lambda as 0.83

In [ ]:
lamda_Arr = np.Array([0.83,0.17,0.83,0.17,0.83])
slices = []
for i in range():


train_Arr = np_Arr[:42,0:6] #X Values
train_Y = np_Arr[:42,6:7] #y column
test_Arr = np_Arr[43:,0:6] 
test_Y = np_Arr[43:,6:7]